Unify the FV3-HRRR and FV3-HRRR-smoke
NOAA-GSL/ccpp-physics pull request #160
Opened 2022-09-02 19:25 UTC by haiqinli

1). The codes of ufs-weather-model/fv3atm/ccpp-physics is based on RRFS_dev for baseE.

2). The FV3_HRRR and FV3_HRRR_smoke are unified as one suite of FV3_HRRR. If the input namelist option rrfs_sd is false, it runs as the standard alone RRFS. IF rrfs_sd is true, it runs with smoke and dust for RRFS-SD. The meteorological fields are identical between the runs with rrfs_sd=T or rrfs_sd=F.

3). There is just one field_table, which contains smoke and dust tracers. We use the rrfs_sd option to control the tracers index. If rrfs_sd is false, only the default tracers of RRFS are read in. If rrfs_sd is true, the smoke and dust tracers for RRFS-SD are added.

4). The dry deposition velocity is an input variable to MYNN PBL.

5). The smoke and dust codes are significantly cleaned and improved.

2022-09-06 14:30 UTC, hu5970 commented
Please review this PR at your earliest convenience. This PR will be a part of RRFS baseline E. Thanks, Ming

2022-09-06 15:00 UTC, zhanglikate approved these changes

2022-09-06 15:29 UTC, SamuelTrahanNOAA approved these changes

2022-09-06 15:29 UTC, SamuelTrahanNOAA commented on physics/module_bl_mynn.F90
> +                   vd1(ic) = 0. ! dry deposition veolocity
```suggestion
                   vd1(ic) = 0. ! dry deposition velocity
```

2022-09-06 15:29 UTC, SamuelTrahanNOAA commented on physics/module_bl_mynn.F90
> +                   vd1(ic) = vdep(i,ic) ! dry deposition veolocity
```suggestion
                   vd1(ic) = vdep(i,ic) ! dry deposition velocity
```

2022-09-06 15:42 UTC, haiqinli commented on physics/module_bl_mynn.F90
> +                   vd1(ic) = vdep(i,ic) ! dry deposition veolocity
Thanks, Sam. It was corrected accordingly.

2022-09-06 17:48 UTC, hu5970 commented
@haiqinli Please merge this one if it is ready. Thanks, Ming

2022-09-06 18:40 UTC, SamuelTrahanNOAA commented
> @haiqinli Please merge this one if it is ready. Thanks, Ming

We need pull requests at the fv3atm and ufs-weather-model level first, otherwise merging to ccpp-physics would accomplish nothing.

Also, we need to run regression tests. Given the urgency of your message, I can run them myself instead of waiting for Jacques. (I'm tasked for emergency support of the parallels).

Hera is down tomorrow, so we need to begin testing today.

2022-09-06 18:45 UTC, SamuelTrahanNOAA commented
The higher-level PRs are here, so I will begin regression tests now:

https://github.com/NOAA-GSL/ufs-weather-model/pull/148
https://github.com/NOAA-GSL/fv3atm/pull/154

2022-09-06 19:19 UTC, SamuelTrahanNOAA commented
This branch does not work; several tests fail to compile or crash. See the ufs-weather-model PR for details:

https://github.com/NOAA-GSL/ufs-weather-model/pull/148

2022-09-18 20:29 UTC, SamuelTrahanNOAA commented on physics/module_bl_mynn.F90
> +       kmaxfire = ceiling(log(frp))
```suggestion
```

2022-09-18 20:31 UTC, SamuelTrahanNOAA requested changes
When frp is 0, code fails with floating point exception.

2022-09-18 20:31 UTC, SamuelTrahanNOAA commented on physics/module_bl_mynn.F90
> +                khdz(k) = MAX(1.1*khdz(k),sqrt((emis_ant_no / NO_threshold)) / dz(k) * rhoz(k)) ! JLS 12/21/21
```suggestion
                kmaxfire = ceiling(log(frp))
                khdz(k) = MAX(1.1*khdz(k),sqrt((emis_ant_no / NO_threshold)) / dz(k) * rhoz(k)) ! JLS 12/21/21
```

2022-09-18 20:37 UTC, SamuelTrahanNOAA commented on physics/module_bl_mynn.F90
> +       kmaxfire = ceiling(log(frp))
Also, a few lines down, you need to insert kmaxfire here:

```
             IF ( frp > frp_threshold ) THEN
                kmaxfire = ceiling(log(frp))
                khdz(k) = MAX(1.1*khdz(k),sqrt((emis_ant_no / NO_threshold)) / dz(k) * rhoz(k)) ! JLS 12/21/21
```

2022-09-18 20:46 UTC, SamuelTrahanNOAA commented
I've found the bugs that cause RRFS to crash early in debug mode. Thanks to that, I was able to run the smoke code in debug mode, and found one bug:

             kmaxfire = ceiling(log(frp))

when frp=0, this results in a floating point exception. The calculation must be moved to within the "if" block:

             IF ( frp > frp_threshold ) THEN
                kmaxfire = ceiling(log(frp))
                khdz(k) = MAX(1.1*khdz(k), (1. - k/(kmaxfire*2.)) * ((log(frp))**2.- 2.*log(frp)) / dz(k)*rhoz(k)) ! JLS 12/21/21

I'm working on a PR to the authoritative to fix the other crashes. The bugs are all in fv_regional_bc.F90

2022-09-23 16:35 UTC, SamuelTrahanNOAA commented
@haiqinli I'm testing some changes to the module_sf_ruclsm bug fixes. These changes were requested by @tanyasmirnova because the bug fixes belong in lsm_ruc.F90 and should also include "snow on ice" sanity checks. I'm doing regression tests now. I don't expect the results to change, but it is possible if a point has an unphysically small amount of snow on ice (<1e-20)

2022-10-05 19:13 UTC, tanyasmirnova approved these changes

2022-10-05 19:14 UTC, tanyasmirnova approved these changes

2022-10-05 23:36 UTC, SamuelTrahanNOAA approved these changes

2022-10-05 23:36 UTC, merged