update physics for RRFS baseline E
NOAA-GSL/ccpp-physics pull request #164
Opened 2022-10-10 16:22 UTC by hu5970

The MYNN and RUCLSM were updated. The code has been tested with retros.
This PR includes three parts:

1)    MYNN code changes from Joe.
2)    Update Thompson MP for reducing the reflectivity bias.
3)    ruclsm updates from Tanya:
    1) add a special treatment to melting hail on the ground after hail storm.
    2) moved parameter for snow over and conductivity definition to the top

2022-10-10 17:18 UTC, hannahcbarnes approved these changes

2022-10-10 21:43 UTC, tanyasmirnova approved these changes

2022-10-10 21:52 UTC, haiqinli approved these changes

2022-10-11 14:24 UTC, joeolson42 approved these changes

2022-10-11 15:51 UTC, SamuelTrahanNOAA requested changes
Smoke debug tests fail with a floating-point exception at line 5353 of module_bl_mynn.F90.

2022-10-11 15:58 UTC, mdtoyNOAA approved these changes

2022-10-11 16:07 UTC, SamuelTrahanNOAA commented
Everyone please examine the diffs more carefully. The line that is failing (5353 of module_bl_mynn.F90) was apparently not supposed to be in the PR, and was inserted by accident during a merge. There may be more such errors.

```
    IF ( rrfs_sd .and. enh_mix ) THEN
       kmaxfire = ceiling(log(frp))  <====== line should not be
```

2022-10-11 16:23 UTC, tanyasmirnova approved these changes
@SamuelTrahanNOAA I reviewed RUC lsm and surface layer MYNN changes, and everything looks good to me.

2022-10-11 16:33 UTC, joeolson42 approved these changes

2022-10-11 17:02 UTC, mdtoyNOAA approved these changes

2022-10-11 17:08 UTC, zhanglikate approved these changes

2022-10-13 14:56 UTC, SamuelTrahanNOAA approved these changes

2022-10-13 14:56 UTC, merged