Number concentration bug and code clean up in GFS_suite_interstitial_4
NOAA-GSL/ccpp-physics pull request #26
Opened 2020-05-08 16:01 UTC by hannahcbarnes

This is a correction for a bug. I also removed some variables that are no longer used in the code. The amount of code changed is very minimal.

2020-05-11 15:06 UTC, climbfuji requested changes
Thanks for cleaning up the argument list and fixing those bugs. This will change the answer for all tests that use Thompson MP, right?

2020-05-11 15:06 UTC, climbfuji commented on physics/GFS_suite_interstitial.F90
> +      gq0, clw, dqdti, errmsg, errflg)
If you remove these variables, please make sure to also remove them from the metadata file.

2020-05-12 20:52 UTC, climbfuji commented
Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/26/files
https://github.com/NOAA-GSD/fv3atm/pull/27
https://github.com/NOAA-GSD/ufs-weather-model/pull/21

For regression testing information, see https://github.com/NOAA-GSD/ufs-weather-model/pull/21.

2020-05-12 23:40 UTC, DomHeinzeller approved these changes

2020-05-13 13:26 UTC, merged