Move plum rise code to GOCART repository
NOAA-GSL/ccpp-physics pull request #87
Opened 2021-04-20 14:19 UTC by climbfuji

This PR removes the four plume rise Fortran modules from ccpp-physics and the dependencies on these from the CCPP metadata files.

Associated PRs:
MISSING

2021-04-22 21:51 UTC, zhanglikate reviewed
why you deleted the  vash_settling_mod.F90 dependency?
Can you reproduce the results when you call the sea salt and plume-rise modules from the process library? Is it bit for bit consistent as calling from the gsdchem part?

2021-04-22 21:58 UTC, DomHeinzeller commented
> why you deleted the vash_settling_mod.F90 dependency?
> Can you reproduce the results when you call the sea salt and plume-rise modules from the process library? Is it bit for bit consistent as calling from the gsdchem part?

I didn't remove any vash_settling dependency, please check again. I only removed "plume_data_mod.F90,plume_rise_mod.F90,plume_scalar_mod.F90,plume_zero_mod.F90" from a bunch of files.

I didn't run against the previous code, but I can do that over the next days when I find the time. It may not be b4b, depending on the compiler flags passed to the gocart library, but we will see.

I can create baselines with this code and verify against it, which means we have run-to-run reproducibility at least.

2021-04-22 22:23 UTC, zhanglikate approved these changes

2021-04-23 01:16 UTC, haiqinli approved these changes

2021-04-23 11:01 UTC, SamuelTrahanNOAA requested changes
If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.

2021-04-23 12:58 UTC, merged